
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    build:
      context: ./EdrServer
    command: celery -A EdrServer.celery worker --loglevel=info
    volumes:
      - ./EdrServer:/usr/src/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=EdrServer.settings
      - PYTHONPATH=/usr/src/app:$PYTHONPATH

  django:
    container_name: django
    build:
      context: ./EdrServer
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000    
    volumes:
      - ./EdrServer:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-ua(v^#pglq@i44b+n7urx86c8htmthj2^j+8j@rm4j471)r2#4
      - ALLOWED_HOSTS=*

volumes:
  redis_data:
