
services:
  redis:
    container_name: redis
    image: redis:alpine
    command: --port 6378
    ports:
      - 6378:6378
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    build:
      context: ./EdrServer
    command: celery -A EdrServer.celery worker --loglevel=info
    volumes:
      - ./EdrServer:/usr/src/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=EdrServer.settings
      - PYTHONPATH=/usr/src/app:$PYTHONPATH
      - CELERY_BROKER_URL=redis://redis:6378/0

  django:
    container_name: django
    build:
      context: ./EdrServer
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8001
    volumes:
      - ./EdrServer:/usr/src/app
    ports:
      - 8001:8001
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-ua(v^#pglq@i44b+n7urx86c8htmthj2^j+8j@rm4j471)r2#4
      - ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=redis://redis:6378/0

volumes:
  redis_data:
