# Generated by Django 5.0.6 on 2024-07-05 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('universal_id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('provider', models.JSONField(blank=True, default=dict)),
                ('event_id', models.IntegerField()),
                ('version', models.IntegerField()),
                ('level', models.IntegerField()),
                ('task', models.IntegerField()),
                ('opcode', models.IntegerField()),
                ('keywords', models.CharField(max_length=200)),
                ('time_created', models.JSONField(blank=True, default=dict)),
                ('event_record_id', models.IntegerField()),
                ('correlation', models.JSONField(blank=True, default=dict)),
                ('execution', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(max_length=200)),
                ('computer', models.CharField(max_length=200)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('event_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
