# Generated by Django 5.0.6 on 2024-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_filtered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
