# Generated by Django 5.0.6 on 2024-06-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_filtered', models.DateTimeField(auto_now_add=True)),
                ('event_universal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.eventitem')),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.ruleitem')),
            ],
        ),
    ]
