# Generated by Django 5.0.6 on 2024-06-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='event_universal_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='rule_id',
            new_name='rule',
        ),
    ]
