# Generated by Django 5.0.6 on 2024-07-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('events', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertItem',
            fields=[
                ('alert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.alert')),
            ],
            bases=('alerts.alert',),
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules.rule')),
            ],
            bases=('rules.rule',),
        ),
    ]
